services:
  - type: web
    name: classifier-frontend
    env: docker
    rootDir: deployment
    dockerContext: Frontend
    dockerfilePath: Frontend/Dockerfile
    plan: free

  - type: web
    name: classifier-backend
    env: docker
    rootDir: deployment
    dockerContext: Backend
    dockerfilePath: Backend/Dockerfile
    plan: free
