services:
  - type: web
    name: askmynotes-frontend
    env: docker
    rootDir: ASK-MY-NOTES-CLASSIFIER
    dockerContext: Frontend
    dockerfilePath: Frontend/Dockerfile
    plan: free

  - type: web
    name: askmynotes-backend
    env: docker
    rootDir: ASK-MY-NOTES-CLASSIFIER
    dockerContext: Backend
    dockerfilePath: Backend/Dockerfile
    plan: free
